version: "1.0"
services:
  bd:
    image: sqlite3
  backend:
    build:
      context: ./server
      dockerfile: ./server.Dockerfile
    volumes:
      - ./server:/app
    expose:
      - 80
    ports:
      - 80
  client:
    build:
      context: ./client
      dockerfile: ./client.Dockerfile