# Generated by Django 5.0.1 on 2024-01-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dish',
            field=models.ManyToManyField(null=True, to='restaurant.menu'),
        ),
    ]
