# Generated by Django 5.0.1 on 2024-01-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_menu_restaurant_restaurant_dish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='dish',
            new_name='menus',
        ),
    ]
