# Generated by Django 5.0.1 on 2024-02-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_dish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='dish',
            field=models.ManyToManyField(null=True, to='restaurant.dish'),
        ),
    ]
