# Generated by Django 5.0.1 on 2024-02-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_dish_category_dishcategory_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='dish',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dishCategory',
            field=models.ManyToManyField(null=True, to='restaurant.dishcategory'),
        ),
    ]
