# Generated by Django 5.0.1 on 2024-02-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_restaurant_dish_restaurant_dishcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishcategory',
            name='image',
        ),
    ]
